export const CALCULATION_ERROR_CODES = {
  DEFINITION_NOT_FOUND: 'CALC_DEFINITION_NOT_FOUND',
  VERSION_NOT_FOUND: 'CALC_VERSION_NOT_FOUND',
  CATEGORY_NOT_FOUND: 'CALC_CATEGORY_NOT_FOUND',
  FORMULA_NOT_FOUND: 'CALC_FORMULA_NOT_FOUND',
  UNIT_NOT_FOUND: 'CALC_UNIT_NOT_FOUND',
  PLUGIN_NOT_FOUND: 'CALC_PLUGIN_NOT_FOUND',
  RESULT_NOT_FOUND: 'CALC_RESULT_NOT_FOUND',
  CERTIFICATE_NOT_FOUND: 'CALC_CERTIFICATE_NOT_FOUND',

  DUPLICATE_SLUG: 'CALC_DUPLICATE_SLUG',
  DUPLICATE_NAME: 'CALC_DUPLICATE_NAME',

  INVALID_INPUT: 'CALC_INVALID_INPUT',
  MISSING_REQUIRED_FIELD: 'CALC_MISSING_REQUIRED_FIELD',
  OUT_OF_RANGE: 'CALC_OUT_OF_RANGE',
  CIRCULAR_DEPENDENCY: 'CALC_CIRCULAR_DEPENDENCY',

  FORMULA_EXECUTION_ERROR: 'CALC_FORMULA_EXECUTION_ERROR',
  FORMULA_PARSE_ERROR: 'CALC_FORMULA_PARSE_ERROR',
  FORMULA_UNDEFINED_VARIABLE: 'CALC_FORMULA_UNDEFINED_VARIABLE',
  FORMULA_TYPE_MISMATCH: 'CALC_FORMULA_TYPE_MISMATCH',

  UNIT_CONVERSION_ERROR: 'CALC_UNIT_CONVERSION_ERROR',
  INCOMPATIBLE_UNITS: 'CALC_INCOMPATIBLE_UNITS',

  AI_REVIEW_FAILED: 'CALC_AI_REVIEW_FAILED',
  PROVIDER_NOT_AVAILABLE: 'CALC_PROVIDER_NOT_AVAILABLE',

  EXECUTION_FAILED: 'CALC_EXECUTION_FAILED',
  DEFINITION_DISABLED: 'CALC_DEFINITION_DISABLED',
  VALIDATION_ERROR: 'CALC_VALIDATION_ERROR',
  ENGINE_VERSION_MISMATCH: 'CALC_ENGINE_VERSION_MISMATCH',
} as const;
